config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'decks#new'
  resources :cards
  resources :decks do
  	resources :energy_levels 
  	collection do 
  		post :create_new_deck
  		post :create_new_deck_with_hearts
  		post :create_new_deck_with_clubs
  		post :create_new_deck_with_diamonds
  		post :create_new_deck_with_spades
  		# post :show_me_card_from_deck
  	end
  end


end

app/models/Array.rb
class Array

	def shuffle(array)
	  counter = array.length - 1

	  while counter > 0
	    # item selected from the unshuffled part of array
	    random_index = rand(counter)

	    # swap the items at those locations
	    array[counter], array[random_index] = array[random_index], array[counter]

	    # de-increment counter
	    counter -= 1
	  end

  	array
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
	belongs_to :deck, optional: true 
	
end

app/models/deck.rb
class Deck < ApplicationRecord
	has_many :cards
	has_many :energy_levels

	RANKS = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

  def create_heart_cards
  	RANKS.each do |rank| 
  		Card.create(suit: "heart", rank: rank, deck_id: self.id)
  	end
  	
  end

  def create_club_cards
  	RANKS.each do |rank| 
  		Card.create(suit: "club", rank: rank, deck_id: self.id)
  	end
  	
  end

  def create_diamond_cards
  	RANKS.each do |rank| 
  		Card.create(suit: "diamond", rank: rank, deck_id: self.id)
  	end
  	
  end

  def create_spade_cards
  	RANKS.each do |rank| 
  		Card.create(suit: "spade", rank: rank, deck_id: self.id)
  	end
  	
  end

  def add_cards_to_deck
		create_heart_cards
		create_club_cards
		create_diamond_cards
		create_spade_cards
	end

	
	def pick_a_card_from_deck
		self.cards.sample
	end


	
end

app/models/energy_level.rb
class EnergyLevel < ApplicationRecord
	belongs_to :deck, optional: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	def index
		@cards = Card.all
	end

	

	def show
		@card = Card.find(params[:id])
	end

	def card_params
		params.require(:card).permit(:suit, :rank)
	end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

	before_action :set_deck, only: [:show]

	# def add_cards
	# 	suits = ["heart", "club", "diamond", "spade"]
	# 	rank = [1..13]
	# 	suits.each do |suit|
	# 		suit 
	# 		rank.each do |rank|
	# 			@deck.card.create(suit: suit, rank: rank)
	# 		end
	# 	end
		
	# end

	def index
		@decks = Deck.all
	end

	def new
		@deck = Deck.new
	end

	def create_new_deck
		@deck = Deck.create!
		@deck.add_cards_to_deck
		redirect_to @deck 
	end

	def show_me_card_from_deck
		@my_card = @deck.cards.sample
		redirect_to card_path(@my_card)
	end

	def add_cards_to_deck
		@deck.add_cards_to_deck
	end

	def create_new_deck_with_hearts
		@deck = Deck.create!
		@deck.create_heart_cards
		redirect_to @deck 
	end

	def create_new_deck_with_clubs
		@deck = Deck.create!
		@deck.create_club_cards
		redirect_to @deck 
	end

	def create_new_deck_with_diamonds
		@deck = Deck.create!
		@deck.create_diamond_cards
		redirect_to @deck 
	end

	def create_new_deck_with_spades
		@deck = Deck.create!
		@deck.create_spade_cards
		redirect_to @deck 
	end

	def create
		@deck = Deck.create()
		add_cards_to_deck
	end

	def show
		@deck = Deck.find(params[:id])
	end

	private 
	def set_deck
		@deck = Deck.find(params[:id])
	end

end

app/controllers/energy_levels_controller.rb
class EnergyLevelsController < ApplicationController

	before_action :set_energy_level, except: [:index]
	before_action :set_deck, except: [:index]

	def index
		@energy_levels = EnergyLevel.all
	end

	def new
	end

	def create
		@energy_level = @deck.energy_levels.create(energy_level_params)

		if @deck.save notice: "One Energy Pod Engaged!!"
		else
			notice: "Oops, error, perhaps another time"
		end
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
	end

	private 
		def set_energy_level
			@energy_level = EnergyLevel.find(params[:id])
		end

		def energy_level_params
			params.require(:comment).permit(:mood_type, :rating)
		end

		def set_deck
			@deck = Deck.find(params[:deck_id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/energy_levels_helper.rb
module EnergyLevelsHelper
end

app/views/cards/index.html.erb
<h1> Welcome to your very own House of Cards </h1> 

<% @cards.each do |card| %> 
	<%= card.rank %> of <%= card.suit %> 
<% end %> 

<h2> Your Random Card is </h2> 

<p>
<%= link_to "click to see the card", @cards.sample %> 
</p> 

app/views/cards/show.html.erb
<h1> I picked this Card </h1> 

<p> <%= @card.rank %> of <%= @card.suit %>s </p>

<p> Don't like this one? <%= link_to "show me another card", card_path(@card.deck.cards.sample) %>  </p>

Task: 

app/views/decks/index.html.erb
<h1> Procrastinators HeadQuarters </h1> 

<h2> Best handled with good music, a glass of something you like (milk?) </h2>

<h3> Instructions </h3>

<p> Options are: </p>
<ol>
	<li>
		I just want a task, and I will do it. Deal me a random task and let's move on. 
		 <%= link_to "Next", new_deck_path %>
	</li>
	
	<li> 
		Just give me fun tasks
		<button> <%= link_to "Next", "#" %></button>
	</li>
	<li> 
		I'm feeling social, give me people tasks
		<button> <%= link_to "Next", "#" %></button>
	</li>
	<li>
		I'm ready to take on the world, give me the difficult tasks 
		<button> <%= link_to "Next", "#" %></button>
	</li>
	<li>
		I'm really procrastinating, let's examine my mood. -- Head to the form below
	</li>
</ol> 

app/views/decks/new.html.erb
<h1> Begin Task Deck </h1>

<p> Regular Deck </p>
<%= button_to "Create Deck of Cards", create_new_deck_decks_path, method: :post %> 

<p> Hearts </p> 
<%= button_to "Create Deck of Cards", create_new_deck_decks_path, method: :post %>

<p> Clubs</p>
<%= button_to "Create Deck of Cards", create_new_deck_decks_path, method: :post %> 

<p> Diamonds </p> 
<%= button_to "Create Deck of Cards", create_new_deck_decks_path, method: :post %> 

<p> Spades </p>
<%= button_to "Create Deck of Cards", create_new_deck_decks_path, method: :post %> 

app/views/decks/show.html.erb
<h1> And we're off to the races! </h1> 

Deck ID: <%= @deck.id %> has <%= @deck.cards.count %> Cards <br> 
<%= image_tag "https://media.giphy.com/media/X8iF4KUWlzYxq/giphy.gif" %> 

<h2> I am ready to do this! </h2>
<%= link_to "show me my card", card_path(@deck.cards.sample) %> 

app/views/energy_levels/_clubs_form.html.erb
<%= form_for([@deck, @deck.energy_levels.build]) do |f| %>
  <div class="form-group">
  <%= f.hidden_field :deck_id %>
  <%= f.hidden_field :mood_type, value: "club" %> 
  </div>
  <div class="form-group">
      <%= f.label "1 to 5" %> 
      <%= f.number_field :target, autofocus: true, class: "form-control", placeholder: "Ambition Level" %>
    </div>
  <div class="actions btn-group">
    <%= f.submit "Submit Comment", class: "btn btn-xs" %>
  </div>
<% end %>

app/views/energy_levels/_diamonds_form.html.erb
<%= form_for([@deck, @deck.energy_levels.build]) do |f| %>
  <div class="form-group">
  <%= f.hidden_field :deck_id %>
  <%= f.hidden_field :mood_type, value: "diamond" %> 
  </div>
  <div class="form-group">
      <%= f.label "1 to 5" %> 
      <%= f.number_field :target, autofocus: true, class: "form-control", placeholder: "Ambition Level" %>
    </div>
  <div class="actions btn-group">
    <%= f.submit "Submit Comment", class: "btn btn-xs" %>
  </div>
<% end %>

app/views/energy_levels/_hearts_form.html.erb
<%= form_for([@deck, @deck.energy_levels.build]) do |f| %>
  <div class="form-group">
  <%= f.hidden_field :deck_id %>
  <%= f.hidden_field :mood_type, value: "heart" %> 
  </div>
  <div class="form-group">
      <%= f.label "1 to 5" %> 
      <%= f.number_field :target, autofocus: true, class: "form-control", placeholder: "Ambition Level" %>
    </div>
  <div class="actions btn-group">
    <%= f.submit "Submit Comment", class: "btn btn-xs" %>
  </div>
<% end %>

<%= form_for([@deck, @deck.energy_levels.build]) do |f| %>
  <div class="form-group">
  <%= f.hidden_field :deck_id %>
  <%= f.hidden_field :mood_type, value: "club" %> 
  </div>
  <div class="form-group">
      <%= f.label "1 to 5" %> 
      <%= f.number_field :target, autofocus: true, class: "form-control", placeholder: "Ambition Level" %>
    </div>
  <div class="actions btn-group">
    <%= f.submit "Submit Comment", class: "btn btn-xs" %>
  </div>
<% end %>

<%= form_for([@deck, @deck.energy_levels.build]) do |f| %>
  <div class="form-group">
  <%= f.hidden_field :deck_id %>
  <%= f.hidden_field :mood_type, value: "diamond" %> 
  </div>
  <div class="form-group">
      <%= f.label "1 to 5" %> 
      <%= f.number_field :target, autofocus: true, class: "form-control", placeholder: "Ambition Level" %>
    </div>
  <div class="actions btn-group">
    <%= f.submit "Submit Comment", class: "btn btn-xs" %>
  </div>
<% end %>

<%= form_for([@deck, @deck.energy_levels.build]) do |f| %>
  <div class="form-group">
  <%= f.hidden_field :deck_id %>
  <%= f.hidden_field :mood_type, value: "spade" %> 
  </div>
  <div class="form-group">
      <%= f.label "1 to 5" %> 
      <%= f.number_field :target, autofocus: true, class: "form-control", placeholder: "Ambition Level" %>
    </div>
  <div class="actions btn-group">
    <%= f.submit "Submit Comment", class: "btn btn-xs" %>
  </div>
<% end %>

app/views/energy_levels/_spades_form.html.erb
<%= form_for([@deck, @deck.energy_levels.build]) do |f| %>
  <div class="form-group">
  <%= f.hidden_field :deck_id %>
  <%= f.hidden_field :mood_type, value: "spade" %> 
  </div>
  <div class="form-group">
      <%= f.label "1 to 5" %> 
      <%= f.number_field :target, autofocus: true, class: "form-control", placeholder: "Ambition Level" %>
    </div>
  <div class="actions btn-group">
    <%= f.submit "Submit Comment", class: "btn btn-xs" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cardgame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>